# Generated by Django 6.0.5 on 2026-07-17 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('required_skills_raw', models.TextField(blank=True, help_text='Comma-separated skills extracted by AI')),
                ('experience_years', models.IntegerField(choices=[(0, 'Entry Level (0-1 years)'), (1, 'Junior (1-3 years)'), (3, 'Mid-Level (3-5 years)'), (5, 'Senior (5-8 years)'), (8, 'Lead (8+ years)')], default=0)),
                ('education_level', models.CharField(choices=[('any', 'Any'), ('diploma', 'Diploma'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD')], default='any', max_length=20)),
                ('jd_file', models.FileField(blank=True, null=True, upload_to='jd_files/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_descriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Description',
                'verbose_name_plural': 'Job Descriptions',
                'ordering': ['-created_at'],
            },
        ),
    ]
