from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import FileResponse, Http404
from .models import HiringReport
from jobs.models import JobDescription
from analysis.models import ResumeAnalysis
from core.ranking import rank_candidates
import io
import os


def generate_pdf_report(job, ranked_analyses):
    """Generate a PDF hiring report using ReportLab."""
    from reportlab.lib.pagesizes import A4
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                     Table, TableStyle, HRFlowable)
    from reportlab.lib.units import cm

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                             topMargin=2*cm, bottomMargin=2*cm,
                             leftMargin=2*cm, rightMargin=2*cm)
    styles = getSampleStyleSheet()
    story = []

    # Title
    title_style = ParagraphStyle('title', parent=styles['Title'],
                                  fontSize=22, spaceAfter=6, textColor=colors.HexColor('#1e3a5f'))
    story.append(Paragraph("HireSense AI — Hiring Report", title_style))
    story.append(Paragraph(f"Job: {job.title}", styles['Heading2']))
    story.append(Spacer(1, 0.3*cm))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor('#4f9cf9')))
    story.append(Spacer(1, 0.5*cm))

    # Summary
    story.append(Paragraph(f"Total Candidates Evaluated: {len(ranked_analyses)}", styles['Normal']))
    story.append(Spacer(1, 0.5*cm))

    # Table header
    data = [['Rank', 'Candidate', 'Email', 'Score', 'Matched Skills', 'Tier']]

    for rank, analysis in ranked_analyses:
        score = analysis.total_score
        if score >= 80:     tier = 'Excellent'
        elif score >= 65:   tier = 'Good'
        elif score >= 50:   tier = 'Average'
        else:               tier = 'Below Avg'

        matched = ', '.join(analysis.get_matched_skills()[:4])
        data.append([
            str(rank),
            analysis.candidate.name or 'Unknown',
            analysis.candidate.email or '-',
            f'{score:.1f}%',
            matched or 'N/A',
            tier,
        ])

    table = Table(data, colWidths=[1.2*cm, 4*cm, 4.5*cm, 1.8*cm, 4.5*cm, 2*cm])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1e3a5f')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 9),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#f0f4ff')]),
        ('FONTSIZE', (0,1), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#cccccc')),
        ('ALIGN', (0,0), (-1,-1), 'CENTER'),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('TOPPADDING', (0,0), (-1,-1), 4),
        ('BOTTOMPADDING', (0,0), (-1,-1), 4),
    ]))
    story.append(table)
    story.append(Spacer(1, 1*cm))
    story.append(Paragraph("Generated by HireSense AI", styles['Italic']))

    doc.build(story)
    buffer.seek(0)
    return buffer


@login_required
def generate_report(request, job_id):
    job = get_object_or_404(JobDescription, pk=job_id)
    analyses = ResumeAnalysis.objects.filter(job=job).select_related('candidate')

    if not analyses.exists():
        messages.warning(request, 'No analyses found for this job. Upload and analyze resumes first.')
        return redirect('job_detail', pk=job_id)

    ranked = rank_candidates(analyses)

    # Generate PDF
    pdf_buffer = generate_pdf_report(job, ranked)

    # Save report record
    from django.core.files.base import ContentFile
    report = HiringReport.objects.create(
        job=job,
        generated_by=request.user,
        top_n_candidates=len(ranked),
    )
    filename = f"report_job_{job.pk}_{report.pk}.pdf"
    report.pdf_file.save(filename, ContentFile(pdf_buffer.read()))
    report.save()

    messages.success(request, 'Hiring report generated successfully!')
    return redirect('report_detail', pk=report.pk)


@login_required
def report_detail(request, pk):
    report = get_object_or_404(HiringReport.objects.select_related('job', 'generated_by'), pk=pk)
    analyses = ResumeAnalysis.objects.filter(job=report.job).select_related('candidate')
    ranked = rank_candidates(analyses)
    return render(request, 'reports/detail.html', {
        'report': report,
        'ranked': ranked,
    })


@login_required
def download_report(request, pk):
    report = get_object_or_404(HiringReport, pk=pk)
    if not report.pdf_file:
        raise Http404("PDF not found.")
    return FileResponse(report.pdf_file.open('rb'), content_type='application/pdf',
                        as_attachment=True, filename=os.path.basename(report.pdf_file.name))
