# Generated by Django 6.0.5 on 2026-07-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('resume_file', models.FileField(upload_to='resumes/')),
                ('raw_text', models.TextField(blank=True, help_text='Full extracted text from resume')),
                ('skills_raw', models.TextField(blank=True)),
                ('education_raw', models.TextField(blank=True)),
                ('experience_raw', models.TextField(blank=True)),
                ('projects_raw', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['-created_at'],
            },
        ),
    ]
