# Generated by Django 6.0.5 on 2026-07-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='fraud_flags_raw',
            field=models.TextField(blank=True, help_text='Comma-separated fraud warning flags'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='fraud_score',
            field=models.IntegerField(default=0),
        ),
    ]
